Repository drum-grammer/docker-pro-2308, pull requests merged in 2023-08, with the labels that each got.

#178 feat : Add Dockerfile and captured image
  mission/니즈/Dockerfile
  mission/니즈/docker-hello-world.png
  mission/니즈/mission.md
Labels: 사전 미션 과제

#180 사전 미션
  mission/jwo0o0/Dockerfile
  mission/jwo0o0/사전미션.md
  mission/jwo0o0/실전미션.png
Labels: 사전 미션 과제

#181 사전미션 완료
  mission/ljt528/Dockerfile
  mission/ljt528/Hello, World!.png
  mission/ljt528/mission.md
Labels: 사전 미션 과제

#183 feat: pre-mission submit
  mission/Yujun-Won/Dockerfile
  mission/Yujun-Won/docker-run.png
  mission/Yujun-Won/pre-mission.md
Labels: 사전 미션 과제

#184 sihyeon 사전 미션 제출
  mission/sleeee/Dockerfile
  mission/sleeee/run-docker-image.png
  mission/sleeee/사전미션.md
Labels: 사전 미션 과제

#182 사전 미션 완료
  mission/yeryung/Dockerfile
  mission/yeryung/Hello_World.png
  mission/yeryung/mission.md
Labels: 사전 미션 과제

#185 사전미션 clear
  mission/gony/dockerfile
  mission/gony/도커실행화면.png
  mission/gony/사전미션.md
Labels: 사전 미션 과제

#187 feat : 사전미션
  mission/jaewon/사전미션.md
Labels: 사전 미션 과제

#191 사전미션
  mission/wonzae/Dockerfile
  mission/wonzae/HelloWorld.png
  mission/wonzae/mission.md.md
Labels: 사전 미션 과제

#192 submit: 사전과제제출(noname2048)
  mission/noname2048/Dockerfile
  mission/noname2048/mission.md
  mission/noname2048/mission.png
Labels: 사전 미션 과제

#196 사전 미션 제출
  mission/lkdcode/Dockerfile
  mission/lkdcode/README.md
  mission/lkdcode/img.png
Labels: 사전 미션 과제

#198 사전 미션 제출
  mission/stc9606/Dockerfile
  mission/stc9606/img.png
  mission/stc9606/img_1.png
  mission/stc9606/mission.md
Labels: 사전 미션 과제, 👍 간결 정확, 🗂️ 좋은 자료 포함

#199 Make : make dockerfile
  mission/HannaRYU/Dockerfile
  mission/HannaRYU/misson.md
  mission/HannaRYU/스크린샷 2023-08-01 오전 9.49.36.png
Labels: 사전 미션 과제

#205 [김해린] 8월 원티드 프리 온보딩 챌린지 - 사전 미션 완료
  mission/haerin/Dockerfile
  mission/haerin/premission.md
  mission/haerin/premissionimage.png
Labels: 사전 미션 과제

#207 [230801][원티드] 프리온보딩 챌린지 8월 백엔드 사전미션 제출
  mission/ung/ung.md
  mission/woolly/Dockerfile
  mission/woolly/사전미션.md
Labels: 사전 미션 과제

#209 온보딩 사전미션
  mission/정찬우/Dockerfile
  mission/정찬우/answer.md
  mission/정찬우/screenshot.png
Labels: 사전 미션 과제

#210 사전 과제 제출입니다.
  mission/ImWonYong/Dockerfile
  mission/ImWonYong/mission.png
  mission/ImWonYong/사전과제.md
Labels: 사전 미션 과제

#212 사전미션
  mission/jin/Dockerfile
  mission/jin/mission.md
  mission/jin/도커실행.png
Labels: 사전 미션 과제

#213 OT execute
  mission/doogunwo/.Dockerfile.un~
  mission/doogunwo/Dockerfile
  mission/doogunwo/result.md
  mission/doogunwo/실습결과.JPG
Labels: 사전 미션 과제

#217 사전미션 제출
  mission/김태영/Dockerfile
  mission/김태영/mission.jpg
  mission/김태영/mission.md
Labels: 사전 미션 과제

#223 콘테스트 참가: 안중훈
  contest/안중훈/Dockerfile
  contest/안중훈/README.md
Labels: 나만의 이미지 만들기 컨테스트

#225 feat : 콘테스트 참가
  contest/jian1114/Dockerfile
  contest/jian1114/README.md
  contest/jian1114/img_api.png
  contest/jian1114/img_ex.png
  contest/jian1114/img_get_api.png
  contest/jian1114/weather.py
Labels: 나만의 이미지 만들기 컨테스트

#226 1회차 과제 제출
  contest/illGiveYouCuteWhale/Dockerfile
  contest/illGiveYouCuteWhale/Main.java
  contest/illGiveYouCuteWhale/README.md
  contest/illGiveYouCuteWhale/docker_images.png
  contest/illGiveYouCuteWhale/docker_run.png
  contest/illGiveYouCuteWhale/homework1.jar
Labels: 나만의 이미지 만들기 컨테스트

#227 1회차 과제제출
  contest/njlee/Dockerfile
  contest/njlee/docker build.png
  contest/njlee/docker run.png
  contest/njlee/formatting.md
  contest/njlee/index.html
Labels: 나만의 이미지 만들기 컨테스트

#231 [Contest 제출] 국가별 날씨 조회 프로그램
  contest/hj_kim97/Dockerfile
  contest/hj_kim97/README.md
  contest/hj_kim97/images/RunningScreen.PNG
  contest/hj_kim97/package-lock.json
  contest/hj_kim97/package.json
  contest/hj_kim97/server.js
Labels: 나만의 이미지 만들기 컨테스트

#232 [contest] feat : lucky-ascii
  contest/do-not-do-that/Dockerfile
  contest/do-not-do-that/README.md
  contest/do-not-do-that/choiceArt.py
Labels: 나만의 이미지 만들기 컨테스트

#235 [Contest] 1회차 과제 제출 : 박세진
  contest/codesejin/Dockerfile
  contest/codesejin/README.md
  contest/codesejin/Timer.java
  contest/codesejin/cli.png
  contest/codesejin/inside.png
  contest/codesejin/source-code.png
  contest/codesejin/timer-app.png
Labels: 나만의 이미지 만들기 컨테스트

#243 사전 과제 제출-kwon
  mission/kkwon/answer.md
  mission/kkwon/도커 생성.png
  mission/kkwon/도커 실행.png
Labels: 사전 미션 과제

#247 사전미션 제출합니다.
  mission/hae02y/Docker.md
  mission/hae02y/Dockerfile
  mission/hae02y/hello-world캡처.JPG
Labels: 사전 미션 과제

#248 사전미션 제출
  mission/chae/Dockerfile
  mission/chae/hello-world.png
  mission/chae/mission.md
Labels: 사전 미션 과제

#99 pre-mission
  mission/true/Dockerfile
  mission/true/helloWorld.png
  mission/true/preMission.md
Labels: 사전 미션 과제, 🙏 수정 필요

#113 사전 과제 제출
  mission/mkwkw/mission.md
Labels: 사전 미션 과제

#71 Ranunclulus mission 다시 제출합니다!
  mission/ranunclulus/mission.md
Labels: 사전 미션 과제

#195 사전 과제 제출합니다.
  mission/yelm-212/Dockerfile
  mission/yelm-212/docker-hello-world.png
  mission/yelm-212/pre-mission.md
Labels: 사전 미션 과제

#175 사전미션
  mission/chaewonlee/.Dockerfile.un~
  mission/chaewonlee/Dockerfile
  mission/chaewonlee/answer.md
  mission/chaewonlee/컨테이너실행캡처.JPG
Labels: 사전 미션 과제

#224 사전미션제출
  mission/lovebokdoll
  mission/이미지 2023. 8. 2. 오후 8.41.jpeg
Labels: 사전 미션 과제, 🙏 수정 필요

#251 [cleaning] 데이터 정리 (디렉토리 이슈)
  mission/lovebokdoll/lovebokdoll.md
  mission/lovebokdoll/이미지 2023. 8. 2. 오후 8.41.jpeg
Labels: 레파지토리 관리

#166 8월 사전과제 제출
  mission/Yoon/Dockerfile
  mission/Yoon/dockerRunImage.png
  mission/Yoon/mission.md
Labels: 사전 미션 과제, 🙏 수정 필요 - 깃 관련 이슈

#174 [박건후] pre_mission
  mission/sbzkdl/Dockerfile
  mission/sbzkdl/pre-mission.png
  mission/sbzkdl/pre_mission.md
Labels: 사전 미션 과제

#200 도커(1)
  Dockerfile
  docker-screenshot.png
  mission.md
  mission/childbaby/2023-08-01 10 25 24.png
  mission/childbaby/2023-08-01 10 29 21.png
  mission/childbaby/Dockerfile
Labels: 사전 미션 과제, 🙏 수정 필요

#253 [cleaning] 데이터 정리 (디렉토리 이슈) 레파지토리 관리
  mission/childbaby/Dockerfile copy
  mission/childbaby/docker-screenshot.png
  mission/childbaby/mission.md
Labels: 레파지토리 관리

#257 Please merge my late assignments
  mission/kimx3966/Dockerfile
  mission/kimx3966/screenshot_mission.png
  mission/kimx3966/사전과제.md
Labels: 사전 미션 과제
