Repository drum-grammer/docker-pro-2308, pull requests merged in 2023-07, with the labels that each got.

#13 사전 미션
  mission/mandy/Dockerfile
  mission/mandy/docker실행화면.png
  mission/mandy/사전미션.md
Labels: 사전 미션 과제

#14 사전미션
  mission/cono/Dockerfile
  mission/cono/docker-screenshot.png
  mission/cono/mission.md
Labels: 사전 미션 과제

#16 사전미션
  mission/jinnykim/dockerfile
  mission/jinnykim/jinnykim-docker-run.PNG
  mission/jinnykim/jinnykim-mission.md
Labels: 사전 미션 과제

#18 사전미션 제출
  mission/ahma0/Dockerfile
  mission/ahma0/answer.md
  mission/ahma0/docker_image.png
Labels: 사전 미션 과제

#19 docs(사전 미션): 사전 미션 제출 - erados
  mission/erados/Dockerfile
  mission/erados/answer.md
  mission/erados/docker-hello-world.png
Labels: 사전 미션 과제

#20 사전과제 제출
  mission/kiesses/Dockerfile
  mission/kiesses/kiesses-hello-world.png.png
  mission/kiesses/kiesses_mission.md
Labels: 사전 미션 과제

#21 사전 미션 제출
  mission/devholic/Dockerfile
  mission/devholic/README.md
  mission/devholic/도커 실행.png
Labels: 사전 미션 과제

#24 사전 미션 제출합니다
  mission/namhuiju/Dockerfile
  mission/namhuiju/README.md
  mission/namhuiju/도커실행화면.png
Labels: 사전 미션 과제

#25 사전 미션 제출
  mission/최영태/Dockerfile
  mission/최영태/docker-hello-world.png
  mission/최영태/사전미션.md
Labels: 사전 미션 과제

#26 사전 미션 제출
  mission/Heomanbo/Dockerfile
  mission/Heomanbo/README.md
  mission/Heomanbo/hello-world.JPG
Labels: 사전 미션 과제

#28 사전미션 제출
  mission/8471919/Dockerfile
  mission/8471919/docker_result.png
  mission/8471919/mission.md
Labels: 사전 미션 과제

#33 Submit mission
  mission/langley1234/Dockerfile
  mission/langley1234/docker.md
  mission/langley1234/docker.png
Labels: 사전 미션 과제

#34 사전 미션 제출
  mission/log97/Dockerfile
  mission/log97/answer.md
  mission/log97/hello-world.PNG
Labels: 사전 미션 과제

#23 pre-mission-by-ghdwlsgur
  mission/ghdwlsgur/Dockerfile
  mission/ghdwlsgur/mission-complete.png
Labels: 사전 미션 과제

#35 jiwonyang 사전 미션 제출
  mission/jiwonyang/Dockerfile
  mission/jiwonyang/jiwonyang_docker_run.png
  mission/jiwonyang/jiwonyang_mission.md
Labels: 사전 미션 과제, 👍 간결 정확

#36 사전 미션 제출합니다!
  mission/hamwoojo/Dockerfile
  mission/hamwoojo/mission.md
  mission/hamwoojo/캡처.png
Labels: 사전 미션 과제

#37 사전 미션 제출
  mission/82user/Dockerfile
  mission/82user/docker-screenshot.png
  mission/82user/mission.md
Labels: 사전 미션 과제

#38 사전과제 제출 입니다!
  mission/joyoonsik/Dockerfile
  mission/joyoonsik/answer.md
  mission/joyoonsik/joyoonsik-mission.png
  mission/namhuiju/도커실행화면.png
Labels: 사전 미션 과제

#40 사전 미션
  mission/EgongD/Answer.md
  mission/EgongD/Dockerfile
  mission/EgongD/img.png
Labels: 사전 미션 과제, 👏 상세

#41 사전미션 수행
  mission/bzun/Dockerfile
  mission/bzun/pre-mission.md
Labels: 사전 미션 과제

#42 사전 미션 제출합니다.
  mission/유다언/Dockerfile
  mission/유다언/dockerimage.png
  mission/유다언/사전미션.md
Labels: 사전 미션 과제

#44 사전미션제출
  mission/yoonheyjung/Dockerfile
  mission/yoonheyjung/answer.md
  mission/yoonheyjung/screenshot.png
Labels: 사전 미션 과제

#45 사전미션완료
  mission/권순세/Dockerfile
  mission/권순세/img.png
  mission/권순세/사전미션서술형답안.md
Labels: 사전 미션 과제

#46 사전 미션 제출
  mission/supark0206/Dockerfile
  mission/supark0206/dockerRun.png
  mission/supark0206/사전미션질문.md
Labels: 사전 미션 과제, 👍 간결 정확

#48 사전미션제출
  mission/ho-yu/Dockerfile
  mission/ho-yu/answer.md
  mission/ho-yu/ho-yu-docker-run.png
Labels: 사전 미션 과제

#49 사전 미션 제출
  mission/nohheeyeon/Dockerfile
  mission/nohheeyeon/image.png
  mission/nohheeyeon/mission.md
Labels: 사전 미션 과제

#53 사전 미션 제출입니다.
  mission/jhyun0227/Dockerfile
  mission/jhyun0227/docker_run.jpg
  mission/jhyun0227/jhyun0227_mission.md
Labels: 사전 미션 과제, 👍 간결 정확

#54 사전과제 제출
  mission/유진수/Dockerfile
  mission/유진수/Mission.md
  mission/유진수/docker_excution.png
Labels: 사전 미션 과제, 👍 간결 정확

#57 사전미션 제출
  mission/seongnakhun/Dockerfile
  mission/seongnakhun/Hello, world.PNG
  mission/seongnakhun/answer.md
Labels: 사전 미션 과제, 👏 간결

#58 feat:pre-mission update
  mission/newh2/Dockerfile
  mission/newh2/helloworld.png
  mission/newh2/pre-mission.md
Labels: 사전 미션 과제

#59 원티드 프리온보딩 백엔드 챌린지 8월 사전과제 제출합니다
  mission/n1ghtsky0/Dockerfile
  mission/n1ghtsky0/answer.md
  mission/n1ghtsky0/hello-world.PNG
Labels: 사전 미션 과제

#60 사전과제 제출
  mission/jorimjoram/Dockerfile
  mission/jorimjoram/실전미션.png
  mission/jorimjoram/사전미션.md
Labels: 사전 미션 과제

#62 사전 미션 제출
  mission/choincnp/Dockerfile
  mission/choincnp/capture.png
  mission/choincnp/onboarding.md
Labels: 사전 미션 과제

#63 사전미션 완료
  mission/jeonghyeon4/Dockerfile
  mission/jeonghyeon4/사전미션 캡쳐.png
  mission/jeonghyeon4/사전미션.md
Labels: 사전 미션 과제

#64 사전미션 수행
  mission/YungIn/Dockerfile
  mission/YungIn/Mission.md
  mission/YungIn/dockerRun.png
Labels: 사전 미션 과제

#67 사전 미션 제출입니다.
  mission/zaew0o0s/Answer.md
  mission/zaew0o0s/Dockerfile
  mission/zaew0o0s/hello_world.JPG
Labels: 사전 미션 과제, 👏 상세

#68 원티드 도커 사전미션 제출
  mission/kmsung/Dockerfile
  mission/kmsung/mission.md
  mission/kmsung/running_screen.jpg
Labels: 사전 미션 과제

#69 사전미션제출
  mission/김여주/Dockerfile
  mission/김여주/docker_img.png
  mission/김여주/사전미션답안.md
  mission/유다언/Dockerfile
  mission/유다언/dockerimage.png
  mission/유다언/사전미션.md
Labels: 사전 미션 과제

#70 원티드 Docker 사전미션 과제 제출드립니다!
  mission/jeonwoojae/Dockerfile
  mission/jeonwoojae/screenshot-docker-run.png
  mission/jeonwoojae/사전미션.md
Labels: 사전 미션 과제, 👏 간결

#72 사전 미션 제출_sonjia
  mission/sonjia/Dockerfile
  mission/sonjia/mission-answer.md
  mission/sonjia/mission-img.png
Labels: 사전 미션 과제

#73 사전과제 제출
  mission/김현지/Docker 결과.png
  mission/김현지/Dockerfile
  mission/김현지/사전미션.md
Labels: 사전 미션 과제, 👏 간결

#74 사전 미션 제출
  mission/Sangyong-Jeon/Dockerfile
  mission/Sangyong-Jeon/image.png
  mission/Sangyong-Jeon/사전미션.md
Labels: 사전 미션 과제, 👍 간결 정확

#75 사전 미션 제출
  mission/teger/Dockerfile
  mission/teger/dockerImage.png
  mission/teger/사전과제.md
Labels: 사전 미션 과제

#15 사전미션 제출
  mission/박진우/Docker 사전 미션.md
  mission/박진우/Dockerfile
  mission/박진우/docker_실행화면1.png
  mission/박진우/docker_실행화면2.png
Labels: 사전 미션 과제, 👏 간결

#27 사전 미션
  mission/홍성민/Dockerfile
  mission/홍성민/answer.md
  mission/홍성민/스크린샷 2023-07-19 오후 2.41.59.png
Labels: 사전 미션 과제

#77 사전과제제출
  Dockerfile
  docker-screenshot.png
  mission.md
Labels: 사전 미션 과제, 👏 간결

#80 사전 미션 제출
  mission/YSPark/Dockerfile
  mission/YSPark/answer.md
  mission/YSPark/hello-world.png
Labels: 사전 미션 과제

#81 사전 미션 제출_kimsuyeon0916
  mission/kimsuyeon0916/Dockerfile
  mission/kimsuyeon0916/docker_run.png
  mission/kimsuyeon0916/pre_mission.md
Labels: 사전 미션 과제

#83 사전과제 제출
  mission/only-juun/Dockerfile
  mission/only-juun/image.png
  mission/only-juun/mission.md
Labels: 사전 미션 과제

#84 사전과제 제출
  mission/hyeonaseome/Dockerfile
  mission/hyeonaseome/docker-screenshot.png
  mission/hyeonaseome/mission.md
Labels: 사전 미션 과제

#86 사전미션 제출
  mission/HJunng/Dockerfile
  mission/HJunng/image.PNG
  mission/HJunng/mission.md
Labels: 사전 미션 과제, 👏 간결

#89 사전과제 제출
  mission/dwseo96/4.도커결과이미지.png
  mission/dwseo96/Dockerfile
  mission/dwseo96/image/misson1.png
  mission/dwseo96/image/misson3.png
  mission/dwseo96/misson.md
Labels: 사전 미션 과제, 👍 간결 정확, 🗂️ 좋은 자료 포함

#92 사전미션
  mission/황봉수/Dockerfile
  mission/황봉수/answer.md
  mission/황봉수/docker_run.png
Labels: 사전 미션 과제

#97 사전미션 제출
  mission/sjiwon/Dockerfile
  mission/sjiwon/question.md
  mission/sjiwon/run.png
Labels: 사전 미션 과제, 👏 상세, 🗂️ 좋은 자료 포함

#79 사전 미션 제출
  mission/cyj/Dockerfile
  mission/cyj/hello-world.png
  mission/cyj/사전미션.md
Labels: 사전 미션 과제

#103 사전 미션 제출
  mission/heewon00/Dockerfile
  mission/heewon00/answer.md
  mission/heewon00/도커실행.png
Labels: 사전 미션 과제

#104 프리온보딩 사전미션 제출!
  Dockerfile
  mission/seinShin/docker_실행.png
  mission/seinShin/premission.md
Labels: 사전 미션 과제

#105 사전미션 완료
  mission/DeadRiceCake/Dockerfile
  mission/DeadRiceCake/mission.jpg
  mission/DeadRiceCake/mission.md
Labels: 👏 간결

#106 이지원 사전미션 수행
  mission/ljw/Dockerfile
  mission/ljw/docker_run_2023-07-27 104136.png
  mission/ljw/misson.md
Labels: 사전 미션 과제

#108 사전미션 제출
  mission/hyunw9/Dockerfile
  mission/hyunw9/mission.md
  mission/hyunw9/screenshot.png
Labels: 사전 미션 과제

#102 pre-mission
  mission/CHITSOO/Dockerfile
  mission/CHITSOO/docker_capture.png
  mission/CHITSOO/mission.md
Labels: 사전 미션 과제, 👏 간결

#110 acycoco mission
  mission/acycoco/Dockerfile
  mission/acycoco/hello-world.png
  mission/acycoco/mission.md
Labels: 사전 미션 과제, 🗂️ 좋은 자료 포함

#112 사전미션 제출
  mission/lwy210/Dockerfile
  mission/lwy210/docker-hello-world.png
  mission/lwy210/misson.md
Labels: 사전 미션 과제

#115 사전 미션 제출합니다
  mission/hyeonsunny/Dockerfile
  mission/hyeonsunny/README.md
  mission/hyeonsunny/capture.png
Labels: 사전 미션 과제

#116 사전 미션 제출
  mission/jeongjiyeon315/Dockerfile
  mission/jeongjiyeon315/answer.md
  mission/jeongjiyeon315/docker-run.png
Labels: 사전 미션 과제

#117 [joyui3906] 8월 원티드 프리 온보딩 챌린지 - docker 뽀개기
  mission/joyui3906/Dockerfile
  mission/joyui3906/pre-mission.md
  mission/joyui3906/pre-mission.png
Labels: 사전 미션 과제

#118 acozy premission submit
  mission/acozy/Dockerfile
  mission/acozy/acozy-container-execute.png
  mission/acozy/acozy-premission.md
Labels: 사전 미션 과제

#119 사전 미션 제출합니다
  mission/seer-lee/Docker.png
  mission/seer-lee/Dockerfile
  mission/seer-lee/mission.md
Labels: 사전 미션 과제

#120 kook3238 commit
  mission/kook3238/Dockerfile
  mission/kook3238/docker.png
  mission/kook3238/kook3238.md
Labels: 사전 미션 과제

#121 ajeong_사전 미션 제출
  ajeong-docker-mission.md
  docker_hello_world_run.png
Labels: 사전 미션 과제

#122 프리온보딩 챌린지 사전미션 PR
  mission/na8i/Dockerfile
  mission/na8i/answer.md
  mission/na8i/docker_run.png
Labels: 사전 미션 과제

#123 사전 미션 제출
  mission/맹지연/Dockerfile
  mission/맹지연/docker.png
  mission/맹지연/mission.md
Labels: 사전 미션 과제

#125 사전미션
  mission/minb/Dockerfile
  mission/minb/hello_world.png
  mission/minb/mission.md
Labels: 사전 미션 과제

#126 사전 미션 제출
  mission/essieng/Dockerfile
  mission/essieng/capture.png
  mission/essieng/mission.md
Labels: 사전 미션 과제, 👍 간결 정확

#127 사전 미션 제출
  mission/Tawook2/Dockerfile
  mission/Tawook2/docker-screenshot.png
  mission/Tawook2/mission.md
Labels: 사전 미션 과제

#128 사전과제 제출
  mission/modory/Dockerfile
  mission/modory/answer.md
  mission/modory/tutorialImg.png
Labels: 사전 미션 과제

#129 사전과제 제출
  mission/마서연/Dockerfile
  mission/마서연/도커 실행.png
  mission/마서연/사전미션.md
Labels: 사전 미션 과제

#131 8월 원티드 프리 온보딩 챌린지 사전미션
  mission/rosie/Dockerfile
  mission/rosie/readme.md
  mission/rosie/도커 실행화면.png
Labels: 사전 미션 과제

#132 사전 미션
  mission/shinmin9812/Dockerfile
  mission/shinmin9812/도커 실행 캡쳐.png
  mission/shinmin9812/사전미션.md
Labels: 사전 미션 과제

#133 8월 원티드 프리 온보딩 챌린지 - docker 뽀개기 사전과제 제출
  mission/s2hoon/Dockerfile
  mission/s2hoon/answer.md
  mission/s2hoon/dockertest.png
Labels: 사전 미션 과제

#134 ho1121h/사전미션
  mission/ho1121h/Dockerfile
  mission/ho1121h/ho1121h.md
  mission/ho1121h/스크린샷.png
Labels: 사전 미션 과제

#137 yun: 8월 원티드 프리 온보딩 챌린지
  mission/yun/Dockerfile
  mission/yun/answer.md
  mission/yun/hello-world.jpg
Labels: 사전 미션 과제

#138 [docs] docker 사전미션
  mission/jsshin6518/Dockerfile
  mission/jsshin6518/jsshin6518_docker_run_image.png
  mission/jsshin6518/pre-mission.md
Labels: 사전 미션 과제

#139 사전 미션 제출
  mission/윤지영/Dockerfile
  mission/윤지영/helloworld.png
  mission/윤지영/premission.md
Labels: 사전 미션 과제

#135 사전 미션 제출
  mission/ybwi0912/Dockerfile
  mission/ybwi0912/[실전 미션] 도커 설치하기.PNG
  mission/ybwi0912/mission.md
Labels: 사전 미션 과제

#141 사전 미션 제출
  mission/achomj/Dockerfile
  mission/achomj/answer.md
  mission/achomj/dockerRun.png
Labels: 사전 미션 과제

#142 사전 미션 제출
  mission/bitnarikim/Dockerfile
  mission/bitnarikim/answer.md
  mission/bitnarikim/hello-world.png
Labels: 사전 미션 과제

#143 feat(): Wanted Docker 온보딩 사전미션 제출
  mission/ung/Dockerfile
  mission/ung/hello_world.png
  mission/ung/ung.md
Labels: 사전 미션 과제

#144 사전미션제출
  mission/honey/Dockerfile
  mission/honey/img.png
  mission/honey/mission.md
Labels: 사전 미션 과제

#145 사전 미션 제출
  mission/gaetokk/Dockerfile
  mission/gaetokk/answer.md
  mission/gaetokk/docker_run.png
Labels: 사전 미션 과제

#146 사전 과제
  mission/jorimjoram/실전미션.png
  mission/rojojun/Dockerfile.txt
  mission/rojojun/rojojun-answer.md
  mission/rojojun/rojojun-docker-result.png
Labels: 사전 미션 과제

#147 [leeseunghee00] 사전 미션 제출
  mission/leeseunghee00/Dockerfile
  mission/leeseunghee00/docker-run.jpg
  mission/leeseunghee00/mission.md
Labels: 사전 미션 과제

#149 사전과제 제출
  mission/binhao22/Answer.md
  mission/binhao22/Dockerfile
  mission/binhao22/docker_run.png
Labels: 사전 미션 과제

#150 사전미션
  mission/haileykim2014/Dockerfile
  mission/haileykim2014/README.md
  mission/haileykim2014/docker-run-image-haileykim2014.jpeg
Labels: 사전 미션 과제

#153 이지수 사전미션
  mission/이지수/Dockerfile
  mission/이지수/HelloWorld.png
  mission/이지수/container.jpeg
  mission/이지수/docker.webp
  mission/이지수/image.png
  mission/이지수/lxc.png
  mission/이지수/mission.md
Labels: 사전 미션 과제, 👍 간결 정확, 🗂️ 좋은 자료 포함

#155 first commit
  mission/1wooo/Dockerfile
  mission/1wooo/도커이미지실행.png
  mission/1wooo/사전미션질문.md
Labels: 사전 미션 과제

#157 사전미션 수행
  mission/sy.cha999/Dockerfile
  mission/sy.cha999/docker_desktop_image_build.PNG
  mission/sy.cha999/docker_desktop_image_run_container_start.PNG
  mission/sy.cha999/docker_image_build_run.PNG
  mission/sy.cha999/mission.md
Labels: 사전 미션 과제, 👍 간결 정확

#160 사전미션 수행
  mission/GaJaMy/Dockerfile
  mission/GaJaMy/answer.md
  mission/GaJaMy/mission4.png
Labels: 사전 미션 과제

#161 사전미션제출
  mission/eunjineee/Dockerfile
  mission/eunjineee/사전미션_eunjineee.assets/image-20230730124201247.png
  mission/eunjineee/사전미션_eunjineee.md
Labels: 사전 미션 과제

#163 feat: Add pre mission
  mission/jaehee/Dockerfile
  mission/jaehee/answer.md
  mission/jaehee/image.png
Labels: 사전 미션 과제

#164 사전미션 제출
  mission/hyeonhe/Dockerfile
  mission/hyeonhe/answer.md
  mission/hyeonhe/capture.png
Labels: 사전 미션 과제

#167 사전미션
  mission/jj/Dockerfile
  mission/jj/mission.md
  mission/jj/도커실행.png
Labels: 사전 미션 과제

#168 사전 미션 제출
  mission/AyoungJo/DockerImage.png
  mission/AyoungJo/Dockerfile
  mission/AyoungJo/사전미션.md
Labels: 사전 미션 과제

#169 사전 미션 제출
  mission/codesejin/Dockerfile
  mission/codesejin/docker-desktop.png
  mission/codesejin/docker-run.png
  mission/codesejin/image,container.png
  mission/codesejin/mission.md
Labels: 사전 미션 과제, 👏 상세, 🗂️ 좋은 자료 포함

#171 사전미션 : 최다연
  mission/최다연/Dockerfile
  mission/최다연/answer.md
  mission/최다연/실행화면.png
Labels: 사전 미션 과제

#172 submit. premission
  mission/pak0426/Dockerfile
  mission/pak0426/img.png
  mission/pak0426/mission.md
Labels: 사전 미션 과제

#176 사전미션완료
  mission/miji-Park/Dockerfile
  mission/miji-Park/docker.md
  mission/miji-Park/docker.png
Labels: 사전 미션 과제
